language: java
dist: trusty

jdk:
- oraclejdk8
- oraclejdk9

cache:
  directories:
  - $HOME/.m2

script:
- ./mvnw test

jobs:
  include:
  - stage: deploy
    jdk: oraclejdk8
    if:
    - repo = gzm55/parent-repositories-maven-extension
    - branch = master
    - type != pull_request
    script: ./mvnw -DskipTests deploy
