language: java
dist: trusty

jdk:
- oraclejdk8
- oraclejdk9

cache:
  directories:
  - "$HOME/.m2"

install: skip

script:
- ./mvnw -B clean install

jobs:
  include:
  - stage: deploy
    jdk: oraclejdk8
    if: repo = gzm55/parent-repositories-maven-extension AND branch = master AND type != pull_request
    before_script:
    - ./mvnw -B -q exec:exec -Dexec.executable=echo -Dexec.args='${project.version}' | grep -q -- '-SNAPSHOT$' || { echo "Skip non SNAPSHOT commits"; travis_terminate 0; }
    script: ./mvnw -B -DskipTests -Dinvoker.skip -gs .mvn/cd-settings.xml deploy
  - stage: deploy
    jdk: oraclejdk8
    if: repo = gzm55/parent-repositories-maven-extension AND tag =~ ^parent-repositories-extension-[0-9]+(\.[0-9]+)+$
    before_script:
    - ./mvnw -B -q exec:exec -Dexec.executable=echo -Dexec.args='${project.version}' | grep -v -q -- '-SNAPSHOT$' || { echo "Skip SNAPSHOT commits"; travis_terminate 0; }
    - gpg --batch --fast-import --passphrase-fd 0 <(openssl aes-256-cbc -K $encrypted_459a6dea2be2_key -iv $encrypted_459a6dea2be2_iv -in .cd/sign.asc.enc -d) <<< "$GPG_PASSWORD"
    script: ./mvnw -B -DskipTests -Dinvoker.skip -gs .mvn/cd-settings.xml -P release-profile deploy
