language: java
dist: trusty

jdk:
- oraclejdk8
- oraclejdk9

env:
  global:
  - secure: FjGuha05PpiexLlb2/50lS4qoMr7km9LqogagBRKBrlVmhaZih9v0igm5HSiUnZuJeCup2kCQophHU0mw9RO4huB1Ssyn/g/dUkRaSh4t5P3pwris2KG1kXUUDg2MRH83jEEOkYCzOlDHomEDBBUd3s8Gc+S+8/AsAUvRHCrLdaUudmvSC0PDlZ0K47aKvt+V78TXbZrDju8uMKMK/KTPr6PrO60BUctt0A6B9V6ikBVbqPboYZY9PRDZ5O8CtwZaBI7ASRNboZH+rwSFoYmWNOH44tHJluzG520EeoSpZalePC9z59lv/4ybefB8KBuItTZ/9c6nBtoTUnO9WDQAT5wleTwoOVyq0YWoAbaV7ea7coTEAKgthItosP4rWvy5ukzIl/bg1Qua7SLh/z00uL8f41S8fP4GVYrynSdZLKe3qNxOlMwYjTnYrQe9r2Gfxt7wlQgc8JGB8OcDaOl7x+8pvDag9Dpen1Fj3N4zBnCxYj8HSoz1zU6A9LoxRsDmHppRzGBqD+Md96WR/4gK3GhpLfOj/oubZQkFQJ9zJAq/TV2g3VPiottbd8D44vcxFjKiUcvX1XiC7d4rNt4x3kNzSaALppCStp/TSLZO4ZXwEk2uC9wkdueTNsNMaeGQmNcPlT/5IgGn91M6A0nr0abLC3VEGKsFfQZGzAwM1A=

cache:
  directories:
  - "$HOME/.m2"

install: skip

script:
- ./mvnw -B clean install

jobs:
  include:
  - stage: deploy
    jdk: oraclejdk8
    if: repo = gzm55/parent-repositories-maven-extension AND branch = master AND type != pull_request
    before_script:
    - ./mvnw -B -q exec:exec -Dexec.executable=echo -Dexec.args='${project.version}' | grep -q -- '-SNAPSHOT$' || { echo "Skip non SNAPSHOT commits"; travis_terminate 0; }
    script: ./mvnw -B -DskipTests -Dinvoker.skip -gs .mvn/cd-settings.xml deploy
  - stage: deploy
    jdk: oraclejdk8
    if: repo = gzm55/parent-repositories-maven-extension AND tag =~ ^parent-repositories-extension-[0-9]+(\.[0-9]+)+$
    before_script:
    - ./mvnw -B -q exec:exec -Dexec.executable=echo -Dexec.args='${project.version}' | grep -v -q -- '-SNAPSHOT$' || { echo "Skip SNAPSHOT commits"; travis_terminate 0; }
    script: ./mvnw -B -DskipTests -Dinvoker.skip -gs .mvn/cd-settings.xml -P release-profile deploy
